$(function(){ var speed=300; var error=0; }); var i=100;
function StartUploadAvatar(){ var upl=document.getElementById("uavatar"); if (upl!="") { document.getElementById('Podstava').className='Podstava2'; JsHttpRequest.query('/modules/users/users-avatar-JSReq.php', {'userpic':upl}, function(result, errors){ if (result){ if (result["Answer"]=="ok"){ document.getElementById('Podstava').className='Podstava1'; document.getElementById('AvatarI').innerHTML="<img src='/userfiles/avatar/"+result["Pic"]+"' />"; } else { document.getElementById('AvatarT').innerHTML="<b>Oops... Либо вы пытались загрузить не фотографию, либо она была слишком большой, либо наш сервер объелся электричества и не хочет работать...</b><pre>"+result["Answer"]+"</pre>";} }},false);}}
function SaveSettings(){ var error=0; var name=$('#uname').val(); var pass=$('#upass').val(); var phone=$('#uphone').val(); var elem=document.getElementById('sendstat'); elem.style.display='block'; if (name=='') { error=1; elem.innerHTML='Ошибка: введите ваше имя!';} if (error==1) { elem.className='ErrorDiv'; } else { elem.className='SaveDiv';elem.innerHTML='Секунду, сохраняем настройки...'; JsHttpRequest.query('/modules/users/users-settings-JSReq.php',{'name':name,'phone':phone,'pass':pass}, function(result,errors){if (result){ if (result["Answer"]=="ok"){ elem.innerHTML='Настройки успешно сохранены.'; elem.className='SuccessDiv'; } else { elem.innerHTML='Внимание! Возникла ошибка...'; elem.className='ErrorDiv'; }}},false); }}
function StartUploadMainPic(){ var upl=document.getElementById("uavatar"); if (upl!="") { document.getElementById('Podstava').className='Podstava4'; $("#mainpicauth").val(''); $("#mainpicauth").hide('normal'); 
JsHttpRequest.query('/modules/users/users-mainpic-JSReq.php', {'userpic':upl}, function(result, errors){ if (result){ if (result["Answer"]!="ok"){$('#MainPicInfo').html("<b>Oops... Возникла ошибка!</b><pre>"+result["Answer"]+"</pre>");} else {
document.getElementById('Podstava').className='Podstava3'; $('#MainPicI').html("<img src='/userfiles/picsquare/"+result["Pic"]+"' />"); $('#mainpicfile').val(result["file"]); $('#mainpicxy').val(result["picxy"]); $("#mainpicauth").val(''); $("#mainpicauth").show('normal');}}}, false); }}
function VerifyFormAdd() { var er=0; $("#ShowError").html(''); $("#ShowError").hide(); var n=$("#newname").val(); if(n==''){ er++; showError("Укажите заголовок статьи", ""); } var d=$("#newds").val();  if(d==''){ er++; showError("Укажите короткое описание (Description)", ""); }
var k=$("#newkw").val();  if(k==''){ er++; showError("Укажите ключевые слова статьи"); } var l=$("#newlid").val();  if(l==''){ er++; showError("Укажите лид статьи (вступление)"); } var c=$("#newcontent").val(); if(c==''){ er++; showError("Введите основное содержание статьи"); } 
var p=$("#mainpicfile").val(); if(p==''){ er++; showError("Загрузите главную фотографию статьи"); } if (er>0) { return false; }} function showError(text) { document.location="#ShowErrorA"; $("#ShowError").show(); $("#ShowError").append("<p>"+text+"</p>"); }
$(document).ready(function() { var uploader = new qq.FineUploader({ element: document.getElementById('uploadercom'), request: { endpoint: '/modules/standart/multiupload/server/handler4.php', paramsInBody: false, },		
callbacks: { onComplete: function(id, fileName, responseJSON) { if(responseJSON.success) { i++; text="<div class='AddAlbumPic' id='divalbumpic"+i+"'><input type='hidden' name='albumpic["+i+"]' value='"+responseJSON.uploadName+"'>";
text=text+"<div class='Photo'><img src='/userfiles/temp/s-"+responseJSON.uploadName+"' /><a href='javascript:void(0);' onclick=\"DeleteAlbumPic("+i+");\" class='DelPic'>Удалить фото</a></div><div class='Areas'>";
text=text+"<input type='text' name='albumname["+i+"]' placeholder='Введите название фотографии' class='UserInpt' style='margin-bottom:10px; width:96%;'>";
text=text+"<input type='text' name='albumauth["+i+"]' placeholder='Введите автора фото или ссылку на источник' class='UserInpt' style='margin-bottom:10px; width:96%;'>";
text=text+"<textarea name='albumtext["+i+"]' class='UserArea' style='height:120px; width:96%;' placeholder='Описание фотографии или просто текст'></textarea>";
text=text+"</div></div>"; $('#uploadercompics').append(text); } if(this.getInProgress()==0) { $(".qq-upload-success").hide("normal"); }}}, debug: false }); });
function DeleteAlbumPic(id) { $('#divalbumpic'+id).hide('slow', function() { $('#divalbumpic'+id).remove(); }); }
